baseURL = '/'
languageCode = 'en-us'
title = 'Lucydevdesign'
theme = 'barcadia'

[menu]
    [[menu.main]]
        name = "Videos"
        URL = "videos"
        weight = 10
    [[menu.main]]
        name = "Projects"
        URL = "projects"
        weight = 20
    [[menu.main]]
        name = "Gallery"
        URL = "gallery"
        weight = 30
    [[menu.main]]
        name = "Contact Me"
        URL = "contact"
        weight = 40
